<?php

namespace ContainerPSCBGJT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8gRHOMJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8gRHOMJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8gRHOMJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BlogController::delete' => ['privates', '.service_locator.IvjZ0JP', 'get_ServiceLocator_IvjZ0JPService', true],
            'App\\Controller\\BlogController::edit' => ['privates', '.service_locator.7smCSn6', 'get_ServiceLocator_7smCSn6Service', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.j2GiTr7', 'get_ServiceLocator_J2GiTr7Service', true],
            'App\\Controller\\BlogController::new' => ['privates', '.service_locator.tcCnIk1', 'get_ServiceLocator_TcCnIk1Service', true],
            'App\\Controller\\BlogController::show' => ['privates', '.service_locator.7smCSn6', 'get_ServiceLocator_7smCSn6Service', true],
            'App\\Controller\\RegistrationController::registration' => ['privates', '.service_locator.q4VmAr8', 'get_ServiceLocator_Q4VmAr8Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\BlogController:delete' => ['privates', '.service_locator.IvjZ0JP', 'get_ServiceLocator_IvjZ0JPService', true],
            'App\\Controller\\BlogController:edit' => ['privates', '.service_locator.7smCSn6', 'get_ServiceLocator_7smCSn6Service', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.j2GiTr7', 'get_ServiceLocator_J2GiTr7Service', true],
            'App\\Controller\\BlogController:new' => ['privates', '.service_locator.tcCnIk1', 'get_ServiceLocator_TcCnIk1Service', true],
            'App\\Controller\\BlogController:show' => ['privates', '.service_locator.7smCSn6', 'get_ServiceLocator_7smCSn6Service', true],
            'App\\Controller\\RegistrationController:registration' => ['privates', '.service_locator.q4VmAr8', 'get_ServiceLocator_Q4VmAr8Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\BlogController::delete' => '?',
            'App\\Controller\\BlogController::edit' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\BlogController::new' => '?',
            'App\\Controller\\BlogController::show' => '?',
            'App\\Controller\\RegistrationController::registration' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BlogController:delete' => '?',
            'App\\Controller\\BlogController:edit' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\BlogController:new' => '?',
            'App\\Controller\\BlogController:show' => '?',
            'App\\Controller\\RegistrationController:registration' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
