<?php

namespace ContainerPSCBGJT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IvjZ0JPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IvjZ0JP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IvjZ0JP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'flashyNotifier' => ['services', 'mercuryseries_flashy.flashy_notifier', 'getMercuryseriesFlashy_FlashyNotifierService', true],
            'task' => ['privates', '.errored.rYa89.r', NULL, 'Cannot determine controller argument for "App\\Controller\\BlogController::delete()": the $task argument is type-hinted with the non-existent class or interface: "App\\Controller\\Task". Did you forget to add a use statement?'],
        ], [
            'flashyNotifier' => '?',
            'task' => '?',
        ]);
    }
}
