<?php

namespace ContainerNfy08er;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7smCSn6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7smCSn6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7smCSn6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.7smCSn6.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.7smCSn6": it references class "App\\Entity\\Article" but no such service exists.'],
            'flashyNotifier' => ['services', 'mercuryseries_flashy.flashy_notifier', 'getMercuryseriesFlashy_FlashyNotifierService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'flashyNotifier' => '?',
        ]);
    }
}
