<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNfy08er\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNfy08er/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNfy08er.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNfy08er\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNfy08er\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nfy08er',
    'container.build_id' => 'fce86c3f',
    'container.build_time' => 1641395693,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNfy08er');
